### ISSUE TITLE
Pull to refresh never completes

### ISSUE THREAD

**Issue by losingkeys** [mmastrac/progscrape-android#1]
Lately when I pull to refresh, it seems to spin forever. I'll even notice it still spinning when I background then re-open the app. If I close the app, I can get a fresh list.

**Comment by mmastrac** [comment]
I've seen this myself a couple of times but it is tough to reproduce. I'll have to get a logcat trace and get more info. Thanks for the report!

**Comment by losingkeys** [comment]
I think I can usually reproduce it. I know how to use adb. Do you have a quick link/explanation on how I can send you a logcat trace?

**Comment by mmastrac** [comment]
No worries right now -- I *think* that what might be happening is that there's either a server error or network flakiness causing the request to fail and the spinner doesn't get nuked in that case. 1.0.5 has a potential fix for this. Ideally you'll see an error message saying that the request failed. I will have to dig into the server to figure out why this is actually failing (assuming that this is what is happening!).

Leaving this bug open until we can confirm.

**Comment by mmastrac** [comment]
I spent the weekend tracking down all the potential causes of this bug and I am pretty sure it is fixed in release 1.0.8 that should be in the store by EOD

**Comment by losingkeys** [comment]
It seems to work for me now. Thanks!
