### ISSUE TITLE
[feature request] Tap logo to scroll to top

### ISSUE THREAD

**Issue by losingkeys** [mmastrac/progscrape-android#3]
Like Twitter's android app :)

**Comment by losingkeys** [comment]
Just updated. Happy to see this in the update. Nice work, thanks!

**Comment by mmastrac** [comment]
Awesome. I think I broke the popup menu color while doing this -- I'll fix that shortly.

**Comment by losingkeys** [comment]
Yeah it's dark grey with black text now. I was going to open an issue. No
worries though, still works like a charm :)
